kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "tasks-pipeline"
spec:
  source:
    contextDir: "openshift-tasks"
    git:
      uri: ${REPO}
  strategy:
    jenkinsPipelineStrategy:
      env:
      - name: GUID
        value: ${GUID}
      - name: CLUSTER
        value: ${CLUSTER}
      jenkinsfilePath: Jenkinsfile
    type: JenkinsPipeline

